# Generated by Django 2.1.7 on 2019-07-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0003_auto_20190704_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qq_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='QQ昵称'),
        ),
    ]
