# Generated by Django 2.1.7 on 2019-07-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0005_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
