# Generated by Django 2.1.7 on 2019-07-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0007_auto_20190710_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(to='Crm.ClassList', verbose_name='已报班级'),
        ),
    ]
